Завдання 1
Створіть одновимірний масив (вектор) з найменшими непарними числами, не менше
15, та виведіть його значення.

In [1]:
import numpy as np

# Створюємо одновимірний масив з непарними числами, починаючи з 15
odd_numbers = np.arange(15, 15 + 2*10, 2)  # Перші 10 непарних чисел починаючи з 15

print(odd_numbers)

[15 17 19 21 23 25 27 29 31 33]


Завдання 2
Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його значеннями
випадкових дійсних чисел від 0 до одиниці.


In [3]:
# Створюємо двовимірний масив розміром 3x3 з випадковими дійсними числами від 0 до 1
matrix = np.random.rand(3, 3)

print(matrix)


[[0.87520105 0.41344175 0.8814256 ]
 [0.46679631 0.61836024 0.58040766]
 [0.19528609 0.20319068 0.00640779]]


Завдання 3
Створіть масив розміром 3x3, заповніть його випадковими дійсними числами від 0 до
1 та знайдіть мін. елемент.

In [4]:
# Створюємо двовимірний масив розміром 3x3 з випадковими дійсними числами від 0 до 1
matrix = np.random.rand(3, 3)

# Знаходимо мінімальний елемент у матриці
min_element = np.min(matrix)

print("Матриця:\n", matrix)
print("Мінімальний елемент:", min_element)

Матриця:
 [[0.92048998 0.89688321 0.30720737]
 [0.17252528 0.28657295 0.84856285]
 [0.07446489 0.7184398  0.21909653]]
Мінімальний елемент: 0.07446489043327187


Завдання 4
Створіть масив розміром 3x3, заповніть його випадковими дійсними числами в
діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить мінімальні елементи в
кожному рядку

In [5]:
# Створюємо двовимірний масив розміром 3x3 з випадковими дійсними числами в діапазоні від 0 до 1
matrix = np.random.rand(3, 3)

# Знаходимо вектор-стовпчик, що містить мінімальні елементи в кожному рядку
min_vector = np.min(matrix, axis=1)

print("Матриця:\n", matrix)
print("Вектор-стовпчик з мінімальними елементами в кожному рядку:\n", min_vector)


Матриця:
 [[0.33894303 0.06787257 0.1384023 ]
 [0.37544724 0.17760619 0.19921683]
 [0.54523239 0.00574461 0.2658263 ]]
Вектор-стовпчик з мінімальними елементами в кожному рядку:
 [0.06787257 0.17760619 0.00574461]


Завдання 5
Створіть два одновимірних масиви розміром 4, заповніть їх випадковими цілими
числами від -5 до 5 та виконайте на них поелементні операції додавання, віднімання
та множення.

In [6]:
# Створюємо два одновимірні масиви розміром 4, заповнені випадковими цілими числами від -5 до 5
array1 = np.random.randint(-5, 6, size=4)
array2 = np.random.randint(-5, 6, size=4)

# Виконуємо поелементні операції додавання, віднімання та множення
addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2

print("Перший масив:", array1)
print("Другий масив:", array2)
print("Поелементне додавання:", addition)
print("Поелементне віднімання:", subtraction)
print("Поелементне множення:", multiplication)

Перший масив: [-4 -5 -1  1]
Другий масив: [-5  2  5  1]
Поелементне додавання: [-9 -3  4  2]
Поелементне віднімання: [ 1 -7 -6  0]
Поелементне множення: [ 20 -10  -5   1]


Завдання 6
Створіть дві матриці 3x3, заповніть їх довільними цілими числами від 1 до 10 та
знайдіть їх добуток

In [7]:
# Створюємо дві матриці розміром 3x3, заповнені випадковими цілими числами від 1 до 10
matrix1 = np.random.randint(1, 11, size=(3, 3))
matrix2 = np.random.randint(1, 11, size=(3, 3))

# Знаходимо добуток двох матриць
product = np.dot(matrix1, matrix2)

print("Перша матриця:\n", matrix1)
print("Друга матриця:\n", matrix2)
print("Добуток матриць:\n", product)

Перша матриця:
 [[2 9 1]
 [2 3 3]
 [1 5 3]]
Друга матриця:
 [[ 6  9 10]
 [ 8  8  5]
 [ 6 10  6]]
Добуток матриць:
 [[ 90 100  71]
 [ 54  72  53]
 [ 64  79  53]]


Завдання 7
Створіть дві матриці розміром 2x3 та 3x3, заповніть їх випадковими цілими числами
в діапазоні від 1 до 4 та перемножте їх між собою.

In [8]:
# Створюємо матрицю розміром 2x3, заповнену випадковими цілими числами від 1 до 4
matrix1 = np.random.randint(1, 5, size=(2, 3))

# Створюємо матрицю розміром 3x3, заповнену випадковими цілими числами від 1 до 4
matrix2 = np.random.randint(1, 5, size=(3, 3))

# Перемножуємо дві матриці
product = np.dot(matrix1, matrix2)

print("Перша матриця (2x3):\n", matrix1)
print("Друга матриця (3x3):\n", matrix2)
print("Добуток матриць:\n", product)

Перша матриця (2x3):
 [[2 3 4]
 [3 4 3]]
Друга матриця (3x3):
 [[4 1 3]
 [1 2 1]
 [4 4 2]]
Добуток матриць:
 [[27 24 17]
 [28 23 19]]


Завдання 8
Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні
від 1 до 12 та знайдіть її обернену матрицю.

In [9]:
# Створюємо матрицю розміром 3x3, заповнену випадковими цілими числами від 1 до 12
matrix = np.random.randint(1, 13, size=(3, 3))

# Знаходимо обернену матрицю
inverse_matrix = np.linalg.inv(matrix)

print("Оригінальна матриця:\n", matrix)
print("Обернена матриця:\n", inverse_matrix)

Оригінальна матриця:
 [[10  5 10]
 [12  8 12]
 [ 8  4  2]]
Обернена матриця:
 [[ 2.66666667e-01 -2.50000000e-01  1.66666667e-01]
 [-6.00000000e-01  5.00000000e-01 -0.00000000e+00]
 [ 1.33333333e-01 -2.46716228e-18 -1.66666667e-01]]


Завдання 9
Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в
діапазоні від -7 до 7 та транспонуйте її.

In [10]:
# Створюємо матрицю розміром 4x4, заповнену випадковими дійсними числами в діапазоні від -7 до 7
matrix = np.random.uniform(-7, 7, size=(4, 4))

# Транспонуємо матрицю
transposed_matrix = np.transpose(matrix)

print("Оригінальна матриця:\n", matrix)
print("Транспонована матриця:\n", transposed_matrix)

Оригінальна матриця:
 [[-1.14171755  3.55066925  2.32800424 -1.74326067]
 [-0.11892381  3.50867348 -6.33995249 -0.19445809]
 [-1.07612576  1.53402996  6.51462564 -3.18483747]
 [ 6.39403429 -4.38197151  1.06794519  4.90841251]]
Транспонована матриця:
 [[-1.14171755 -0.11892381 -1.07612576  6.39403429]
 [ 3.55066925  3.50867348  1.53402996 -4.38197151]
 [ 2.32800424 -6.33995249  6.51462564  1.06794519]
 [-1.74326067 -0.19445809 -3.18483747  4.90841251]]


Завдання 10
Створіть матрицю розміром 3x4 та вектор розміром 4x1, заповніть матрицю
випадковими дійсними числами від 0 до 1, а вектор - випадковими дійсними числами
від 0 до 1, і знайдіть добуток матриці на вектор.

In [11]:
# Створюємо матрицю розміром 3x4 з випадковими числами від 0 до 1
matrix = np.random.rand(3, 4)

# Створюємо вектор розміром 4x1 з випадковими числами від 0 до 1
vector = np.random.rand(4, 1)

# Знаходимо добуток матриці на вектор
result = np.dot(matrix, vector)

print("Матриця:")
print(matrix)
print("\nВектор:")
print(vector)
print("\nДобуток матриці на вектор:")
print(result)

Матриця:
[[0.51683403 0.31023086 0.44698217 0.59696781]
 [0.25690977 0.79712749 0.75031252 0.45804039]
 [0.85190366 0.47925721 0.3634754  0.70931722]]

Вектор:
[[0.77514863]
 [0.94124054]
 [0.27796791]
 [0.02968813]]

Добуток матриці на вектор:
[[0.83459462]
 [1.17159313]
 [1.23354108]]


Завдання 11
Створіть матрицю розміром 2x3 та вектор розміром 3x1, заповніть матрицю
випадковими дійсними числами від 0 до 1, а вектор - випадковими цілими числами в
діапазоні від 1 до 10, і знайдіть добуток матриці на вектор.

In [12]:
# Створюємо матрицю розміром 2x3 з випадковими дійсними числами від 0 до 1
matrix = np.random.rand(2, 3)

# Створюємо вектор розміром 3x1 з випадковими цілими числами від 1 до 10
vector = np.random.randint(1, 11, size=(3, 1))

# Знаходимо добуток матриці на вектор
result = np.dot(matrix, vector)

print("Матриця:")
print(matrix)
print("\nВектор:")
print(vector)
print("\nДобуток матриці на вектор:")
print(result)

Матриця:
[[0.51432418 0.15228606 0.39184618]
 [0.51955328 0.46436176 0.80650378]]

Вектор:
[[5]
 [3]
 [4]]

Добуток матриці на вектор:
[[4.59586381]
 [7.21686681]]


Завдання 12
Створіть дві матриці розміром 9x9, заповніть їх випадковими цілими числами в
діапазоні від 1 до 10 та знайдіть відношення елементів другого стовпця другої матриці
до відповідних елементів першої матриці (поелементне ділення).

In [13]:
# Створюємо дві матриці розміром 9x9 з випадковими цілими числами від 1 до 10
matrix1 = np.random.randint(1, 11, size=(9, 9))
matrix2 = np.random.randint(1, 11, size=(9, 9))

# Вибираємо другий стовпець другої матриці
column2_matrix2 = matrix2[:, 1]

# Відношення елементів другого стовпця другої матриці до відповідних елементів першої матриці
# Ділимо елементи другого стовпця другої матриці на відповідні елементи першої матриці
result = column2_matrix2 / matrix1[:, 1]

print("Матриця 1:")
print(matrix1)
print("\nМатриця 2:")
print(matrix2)
print("\nВідношення елементів другого стовпця другої матриці до відповідних елементів першої матриці:")
print(result)

Матриця 1:
[[ 1  3  7  1  1  4  8  1  9]
 [ 8  4  9  8  2  2  9  8  3]
 [ 7 10  7  6  9  3  5  9  9]
 [ 5  3  4  3  4  2  4  6  5]
 [ 4  4  8  5  4  5 10  2  2]
 [ 8  9  6  3  8  7  2  9  3]
 [ 5  4  1  2  7  6  3  4  1]
 [ 1  3  3  9  2  8 10  4  4]
 [ 1 10  3  5  5 10  6  3 10]]

Матриця 2:
[[ 1  2  5  2 10  3  6  1  7]
 [ 6  8 10 10  8  4  4  1  2]
 [ 5  7  6  2  4 10  7  1  9]
 [10  5  5  6  1  1  6  2  6]
 [ 2 10  2  3  4  6  1  4  2]
 [ 1  2  4  6  7  2 10  1  7]
 [ 7  2  4 10  3  2 10  2  6]
 [ 2  6 10  4  5  1  9  9  5]
 [ 9  7  8  5  1  6  4  2  8]]

Відношення елементів другого стовпця другої матриці до відповідних елементів першої матриці:
[0.66666667 2.         0.7        1.66666667 2.5        0.22222222
 0.5        2.         0.7       ]


Завдання 13
Створіть дві матриці розміром 3x3, заповніть їх випадковими цілими числами в
діапазоні від 1 до 10 та знайдіть добуток їх елементів.

In [14]:
# Створюємо дві матриці розміром 3x3 з випадковими цілими числами від 1 до 10
matrix1 = np.random.randint(1, 11, size=(3, 3))
matrix2 = np.random.randint(1, 11, size=(3, 3))

# Обчислюємо добуток елементів обох матриць
product_matrix1 = np.prod(matrix1)
product_matrix2 = np.prod(matrix2)

print("Матриця 1:")
print(matrix1)
print("\nДобуток елементів матриці 1:")
print(product_matrix1)

print("\nМатриця 2:")
print(matrix2)
print("\nДобуток елементів матриці 2:")
print(product_matrix2)

Матриця 1:
[[ 3  3  1]
 [ 6  5 10]
 [10  2  8]]

Добуток елементів матриці 1:
432000

Матриця 2:
[[9 7 1]
 [3 1 7]
 [1 6 6]]

Добуток елементів матриці 2:
47628


Завдання 14
Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні
від 1 до 5та знайдіть середнє геометричне значення елементів матриці.

In [18]:
# Створюємо матрицю розміром 3x3 з випадковими цілими числами від 1 до 5
matrix = np.random.randint(1, 6, size=(3, 3))

# Розгортаємо матрицю в одномірний масив
matrix_flat = matrix.flatten()

# Обчислюємо добуток всіх елементів
product = np.prod(matrix_flat)

# Обчислюємо середнє геометричне значення
geo_mean = product ** (1 / len(matrix_flat))

print("Матриця:")
print(matrix)
print("\nСереднє геометричне значення елементів матриці:")
print(geo_mean)

Матриця:
[[1 1 4]
 [1 5 3]
 [4 5 2]]

Середнє геометричне значення елементів матриці:
2.3745374686583927


Завдання 15
Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в
діапазоні від -2 до 2 та знайдіть вектор-стовпчик, що містить найменше за модулем
ціле значення в кожному рядку матриці.

In [19]:
# Створюємо матрицю розміром 3x3 з випадковими дійсними числами від -2 до 2
matrix = np.random.uniform(-2, 2, size=(3, 3))

# Округлюємо матрицю до найближчих цілих чисел
matrix_rounded = np.round(matrix).astype(int)

# Знаходимо найменше за модулем ціле число в кожному рядку
min_abs_in_rows = np.sign(matrix_rounded) * np.min(np.abs(matrix_rounded), axis=1)

# Створюємо вектор-стовпчик
result_vector = min_abs_in_rows.reshape(-1, 1)

print("Матриця:")
print(matrix)
print("\nОкруглена матриця:")
print(matrix_rounded)
print("\nВектор-стовпчик з найменшими за модулем цілими числами в кожному рядку:")
print(result_vector)

Матриця:
[[ 0.88911083  1.44440097 -0.83176774]
 [-1.25831958  1.77138826  0.12828739]
 [ 1.10539362  0.64296373 -0.26136698]]

Округлена матриця:
[[ 1  1 -1]
 [-1  2  0]
 [ 1  1  0]]

Вектор-стовпчик з найменшими за модулем цілими числами в кожному рядку:
[[ 1]
 [ 0]
 [ 0]
 [-1]
 [ 0]
 [ 0]
 [ 1]
 [ 0]
 [ 0]]
